// <auto-generated />
using System;
using Company.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.Migrations
{
    [DbContext(typeof(CompanyContext))]
    partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Company.Models.Department.DepartmentModel", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentDepartmentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentName = "Отдел по обслуживанию клиентов"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentName = "Производственный отдел"
                        },
                        new
                        {
                            ID = 3,
                            DepartmentName = "Бухгалтерия"
                        },
                        new
                        {
                            ID = 4,
                            DepartmentName = "Отдел продаж",
                            ParentDepartmentID = 1
                        },
                        new
                        {
                            ID = 5,
                            DepartmentName = "Отдел оптовых продаж",
                            ParentDepartmentID = 4
                        },
                        new
                        {
                            ID = 6,
                            DepartmentName = "Отдел розничных продаж",
                            ParentDepartmentID = 4
                        },
                        new
                        {
                            ID = 7,
                            DepartmentName = "Отдел логистики",
                            ParentDepartmentID = 1
                        },
                        new
                        {
                            ID = 8,
                            DepartmentName = "Склад",
                            ParentDepartmentID = 7
                        },
                        new
                        {
                            ID = 9,
                            DepartmentName = "Отдел доставки",
                            ParentDepartmentID = 7
                        },
                        new
                        {
                            ID = 10,
                            DepartmentName = "Инженерный отдел",
                            ParentDepartmentID = 2
                        },
                        new
                        {
                            ID = 11,
                            DepartmentName = "Отдел контроля качества",
                            ParentDepartmentID = 2
                        },
                        new
                        {
                            ID = 12,
                            DepartmentName = "Отдел закупок",
                            ParentDepartmentID = 2
                        });
                });

            modelBuilder.Entity("Company.Models.Employee.EmployeeModel", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DepartmentID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Age = "28",
                            DepartmentID = 3,
                            Name = "Алексей",
                            Number = "+79123456789",
                            Surname = "Иванов"
                        },
                        new
                        {
                            ID = 2,
                            Age = "32",
                            DepartmentID = 3,
                            Name = "Екатерина",
                            Number = "+79123456780",
                            Surname = "Смирнова"
                        },
                        new
                        {
                            ID = 3,
                            Age = "21",
                            DepartmentID = 5,
                            Name = "Дмитрий",
                            Number = "+79123456781",
                            Surname = "Козлов"
                        },
                        new
                        {
                            ID = 4,
                            Age = "35",
                            DepartmentID = 5,
                            Name = "Анна",
                            Number = "+79123456782",
                            Surname = "Петрова"
                        },
                        new
                        {
                            ID = 5,
                            Age = "43",
                            DepartmentID = 6,
                            Name = "Сергей",
                            Number = "+79123456783",
                            Surname = "Михайлов"
                        },
                        new
                        {
                            ID = 6,
                            Age = "26",
                            DepartmentID = 6,
                            Name = "Ольга",
                            Number = "+79123456784",
                            Surname = "Соколова"
                        },
                        new
                        {
                            ID = 7,
                            Age = "29",
                            DepartmentID = 8,
                            Name = "Иван",
                            Number = "+79123456785",
                            Surname = "Новиков"
                        },
                        new
                        {
                            ID = 8,
                            Age = "31",
                            DepartmentID = 8,
                            Name = "Анастасия",
                            Number = "+79123456786",
                            Surname = "Федорова"
                        },
                        new
                        {
                            ID = 9,
                            Age = "40",
                            DepartmentID = 9,
                            Name = "Александр",
                            Number = "+79123456787",
                            Surname = "Морозов"
                        },
                        new
                        {
                            ID = 10,
                            Age = "27",
                            DepartmentID = 9,
                            Name = "Юлия",
                            Number = "+79123456788",
                            Surname = "Волкова"
                        },
                        new
                        {
                            ID = 11,
                            Age = "33",
                            DepartmentID = 9,
                            Name = "Михаил",
                            Number = "+79123456777",
                            Surname = "Алексеев"
                        },
                        new
                        {
                            ID = 12,
                            Age = "45",
                            DepartmentID = 9,
                            Name = "Елена",
                            Number = "+79123456776",
                            Surname = "Лебедева"
                        },
                        new
                        {
                            ID = 13,
                            Age = "39",
                            DepartmentID = 9,
                            Name = "Андрей",
                            Number = "+79123456775",
                            Surname = "Семенов"
                        },
                        new
                        {
                            ID = 14,
                            Age = "23",
                            DepartmentID = 10,
                            Name = "Мария",
                            Number = "+79123456774",
                            Surname = "Егорова"
                        },
                        new
                        {
                            ID = 15,
                            Age = "41",
                            DepartmentID = 10,
                            Name = "Владимир",
                            Number = "+79123456773",
                            Surname = "Павлов"
                        },
                        new
                        {
                            ID = 16,
                            Age = "30",
                            DepartmentID = 10,
                            Name = "Евгения",
                            Number = "+79123456772",
                            Surname = "Ковалева"
                        },
                        new
                        {
                            ID = 17,
                            Age = "37",
                            DepartmentID = 10,
                            Name = "Николай",
                            Number = "+79123456771",
                            Surname = "Орлов"
                        },
                        new
                        {
                            ID = 18,
                            Age = "34",
                            DepartmentID = 11,
                            Name = "Татьяна",
                            Number = "+79123456770",
                            Surname = "Андреева"
                        },
                        new
                        {
                            ID = 19,
                            Age = "42",
                            DepartmentID = 11,
                            Name = "Павел",
                            Number = "+79123456769",
                            Surname = "Макаров"
                        },
                        new
                        {
                            ID = 20,
                            Age = "22",
                            DepartmentID = 12,
                            Name = "Алиса",
                            Number = "+79123456768",
                            Surname = "Николаева"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole<string>");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser<string>");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Admin",
                            UserId = "d2a2170f-1a1b-4341-81d3-af3088a22402"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole<string>");

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "ff409fbd-0aea-4c5d-acca-7c6e02f7445e",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "f075da41-8929-4807-9dfa-b0b9a84de098",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "d4f1bb5a-fafd-465f-a54f-2510bf379c58",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("Company.Models.ApplicationUserModel", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser<string>");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("ApplicationUserModel");

                    b.HasData(
                        new
                        {
                            Id = "d2a2170f-1a1b-4341-81d3-af3088a22402",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b5d448ea-0d80-44c3-95e5-5bdd0b9c05a2",
                            Email = "putinvodkagta@yandex.by",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "PUTINVODKAGTA@YANDEX.BY",
                            NormalizedUserName = "PUTINVODKAGTA@YANDEX.BY",
                            PasswordHash = "AQAAAAIAAYagAAAAEDHhCwj3vdAZ+8HkJt6+R/FthrKsnDZ3QAuDM36ysFiVoqMy2LIEyFmbdnYiMRKjmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ddb1a014-e91f-49f0-815d-ee9505a09eac",
                            TwoFactorEnabled = false,
                            UserName = "putinvodkagta@yandex.by"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
